version: "3"
services:
  api-server:
    image: api-server
    build: ./backend/
    ports:
      - "4000:4000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27018:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local